### ISSUE TITLE
Proxyscotch response fail 

### ISSUE THREAD

**Issue by thanhhactld** [hoppscotch/proxyscotch#76]
Hi , I'm appreciate about your hard work. 
Currently, i'm trying to use latest proxyscotch docker image to resolve CORS https request from hoppscotch web client. 
But i received error response from proxy like under picture.
![image](https://github.com/hoppscotch/proxyscotch/assets/26387724/4f816bc0-4d09-43ab-966e-eb2dbceac519)

Could you help me or tell me what I am doing wrong ?

There is my docker-compose to deploy proxy

```
version: "3.2"
services:
  proxy_server:
    image: hoppscotch/proxyscotch
    command: ["sh", "-c", "/etc/proxyscotch/out/linux-server/proxyscotch-server-* --host 0.0.0.0:9159 --allowed-origins *"]
    ports:
      - 9159:9159
```
